import os
import json
import time
import hashlib
import requests
import threading
from flask import Flask, request, jsonify, Response
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# --- SECURITY CONFIG ---
# This "SALT" must match exactly what is in your Frontend HTML
SECRET_SALT = "vincent-v3-secure-salt-2026" 

# DeepAI Config
DEEPAI_URL = "https://api.deepai.org/hacking_is_a_serious_crime"
DEEPAI_KEY = "tryit-48957598737-7bf6498cad4adf00c76eb3dfa97dc26d"

# --- HELPER: Verify Token ---
def verify_token(msg_id, token):
    """
    Re-creates the hash on the server side to verify the request is legitimate.
    Logic: SHA256(msg_id + SECRET_SALT)
    """
    if not msg_id or not token:
        return False
    
    # Create the hash exactly how the frontend does
    raw_string = f"{msg_id}{SECRET_SALT}"
    expected_token = hashlib.sha256(raw_string.encode()).hexdigest()
    
    return token == expected_token

# --- KEEP-ALIVE ---
def keep_alive():
    time.sleep(10)
    app_url = os.environ.get('RENDER_EXTERNAL_URL')
    if app_url:
        print(f"Starting keep-alive for {app_url}")
        while True:
            try:
                time.sleep(800)
                requests.get(f"{app_url}/health")
            except:
                pass
threading.Thread(target=keep_alive, daemon=True).start()

# --- ROUTES ---

@app.route('/health', methods=['GET'])
def health():
    return "OK", 200

@app.route('/chat', methods=['POST'])
def chat():
    try:
        data = request.json
        
        # 1. EXTRACT SECURITY FIELDS
        msg_id = data.get('id')      # The UUID generated by frontend
        token = data.get('token')    # The SHA256 hash generated by frontend
        
        # 2. VERIFY TOKEN
        if not verify_token(msg_id, token):
            return jsonify({"error": "⛔ 403 Forbidden: Invalid Security Token"}), 403

        # 3. IF VALID, PROCEED
        message = data.get('message', '')
        model = data.get('model', 'DeepSeek V3.2')
        
        payload = {
            "chat_style": "chat",
            "chatHistory": json.dumps([{"role": "user", "content": message}]),
            "model": model,
            "hacker_is_stinky": "very_stinky",
            "enabled_tools": json.dumps(["image_generator", "image_editor"])
        }

        headers = {
            "api-key": DEEPAI_KEY,
            "Origin": "https://deepai.org",
            "Referer": "https://deepai.org/",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
        }

        r = requests.post(DEEPAI_URL, data=payload, headers=headers)
        return Response(r.text, mimetype='text/plain')

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 10000))
    app.run(host='0.0.0.0', port=port)
